In [1]:
import pandas as pd

In [2]:
austin_csv_path = "Resources/Austin_Crime.csv"

In [3]:
#import the data into a pandas dataframe

crime_df = pd.read_csv(austin_csv_path)
crime_df

,Incident Number,Highest Offense Description,Highest Offense Code,Family Violence,Occurred Date Time,Occurred Date,Occurred Time,Report Date Time,Report Date,Report Time,...,Census Tract,Clearance Status,Clearance Date,UCR Category,Category Description,X-coordinate,Y-coordinate,Latitude,Longitude,Location
0,201012121,FAMILY DISTURBANCE,3400,N,01/01/2010 06:00:00 PM,01/01/2010,1800,01/01/2010 06:00:00 PM,01/01/2010,1800,...,NaN,N,01/08/2010,NaN,NaN,3129781.0,3129781.0,30.224783,-97.694979,"(30.22478271, -97.69497855)"
1,201010159,FAMILY DISTURBANCE,3400,N,01/01/2010 12:27:00 PM,01/01/2010,1227,01/01/2010 12:27:00 PM,01/01/2010,1227,...,NaN,N,02/14/2010,NaN,NaN,3130429.0,3130429.0,30.233996,-97.692674,"(30.23399568, -97.69267436)"
2,201012437,AGG ASSAULT FAM/DATE VIOLENCE,402,Y,01/01/2010 08:57:00 PM,01/01/2010,2057,01/01/2010 09:49:00 PM,01/01/2010,2149,...,NaN,O,01/04/2010,13A,Aggravated Assault,3110704.0,3110704.0,30.224943,-97.755393,"(30.22494313, -97.75539331)"
3,20135001226,IDENTITY THEFT,4022,N,01/01/2010 09:24:00 AM,01/01/2010,924,01/09/2013 09:24:00 AM,01/09/2013,924,...,NaN,N,01/11/2013,NaN,NaN,3122810.0,3122810.0,30.283700,-97.715460,"(30.28370017, -97.71545967)"
4,201010801,PUBLIC INTOXICATION,2300,N,01/01/2010 03:20:00 AM,01/01/2010,320,01/01/2010 04:31:00 AM,01/01/2010,431,...,NaN,C,01/04/2010,NaN,NaN,3128120.0,3128120.0,30.219775,-97.700376,"(30.21977538, -97.70037566)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213133,202020693,BURGLARY OF VEHICLE,601,N,01/01/2020 08:07:00 PM,01/01/2020,2007,01/02/2020 12:25:00 PM,01/02/2020,1225,...,NaN,N,01/20/2020,23F,Theft,3127250.0,3127250.0,30.280806,-97.701468,"(30.28080624, -97.70146796)"
1213134,202012015,ASSAULT W/INJURY-FAM/DATE VIOL,900,Y,01/01/2020 07:19:00 PM,01/01/2020,1919,01/01/2020 07:19:00 PM,01/01/2020,1919,...,NaN,N,01/21/2020,NaN,NaN,3130949.0,3130949.0,30.331740,-97.688350,"(30.33173988, -97.6883503)"
1213135,2020540578,AGG ASLT STRANGLE/SUFFOCATE,410,Y,01/01/2020 12:30:00 PM,01/01/2020,1230,01/01/2020 12:30:00 PM,01/01/2020,1230,...,NaN,N,02/24/2020,13A,Aggravated Assault,3130124.0,3130124.0,30.219903,-97.694026,"(30.2199032, -97.69402556)"
1213136,202011513,DISCLOSE/PROMO INTIMATE VISUAL,2610,N,01/01/2020 01:15:00 PM,01/01/2020,1315,01/01/2020 01:15:00 PM,01/01/2020,1315,...,NaN,N,03/05/2020,NaN,NaN,0.0,0.0,NaN,NaN,NaN
1213137,20205001615,THEFT,600,N,01/01/2020 12:00:00 PM,01/01/2020,1200,01/13/2020 11:59:00 AM,01/13/2020,1159,...,NaN,N,03/06/2020,23H,Theft,3089085.0,3089085.0,30.158438,-97.825589,"(30.15843807, -97.82558909)"

In [4]:
# Set new index to Date of Occurrence
df = crime_df.set_index("Report Date")
df.head()

,Incident Number,Highest Offense Description,Highest Offense Code,Family Violence,Occurred Date Time,Occurred Date,Occurred Time,Report Date Time,Report Time,Location Type,...,Census Tract,Clearance Status,Clearance Date,UCR Category,Category Description,X-coordinate,Y-coordinate,Latitude,Longitude,Location
Report Date,,,,,,,,,,,,,,,,,,,,,
01/01/2010,201012121,FAMILY DISTURBANCE,3400,N,01/01/2010 06:00:00 PM,01/01/2010,1800,01/01/2010 06:00:00 PM,1800,RESIDENCE / HOME,...,NaN,N,01/08/2010,NaN,NaN,3129781.0,3129781.0,30.224783,-97.694979,"(30.22478271, -97.69497855)"
01/01/2010,201010159,FAMILY DISTURBANCE,3400,N,01/01/2010 12:27:00 PM,01/01/2010,1227,01/01/2010 12:27:00 PM,1227,RESIDENCE / HOME,...,NaN,N,02/14/2010,NaN,NaN,3130429.0,3130429.0,30.233996,-97.692674,"(30.23399568, -97.69267436)"
01/01/2010,201012437,AGG ASSAULT FAM/DATE VIOLENCE,402,Y,01/01/2010 08:57:00 PM,01/01/2010,2057,01/01/2010 09:49:00 PM,2149,RESIDENCE / HOME,...,NaN,O,01/04/2010,13A,Aggravated Assault,3110704.0,3110704.0,30.224943,-97.755393,"(30.22494313, -97.75539331)"
01/09/2013,20135001226,IDENTITY THEFT,4022,N,01/01/2010 09:24:00 AM,01/01/2010,924,01/09/2013 09:24:00 AM,924,RESIDENCE / HOME,...,NaN,N,01/11/2013,NaN,NaN,3122810.0,3122810.0,30.283700,-97.715460,"(30.28370017, -97.71545967)"
01/01/2010,201010801,PUBLIC INTOXICATION,2300,N,01/01/2010 03:20:00 AM,01/01/2010,320,01/01/2010 04:31:00 AM,431,RESIDENCE / HOME,...,NaN,C,01/04/2010,NaN,NaN,3128120.0,3128120.0,30.219775,-97.700376,"(30.21977538, -97.70037566)"

In [5]:
date_loc = df.loc[:, ["Latitude", "Longitude"]].head()
date_loc

              Latitude  Longitude
Report Date
01/01/2010   30.224783 -97.694979
01/01/2010   30.233996 -97.692674
01/01/2010   30.224943 -97.755393
01/09/2013   30.283700 -97.715460
01/01/2010   30.219775 -97.700376